Iter13
arturturundaev/shorturl pull request #8
Opened 2024-08-13 12:23 UTC by arturturundaev

2024-08-14 08:08 UTC, tmvrus requested changes
К сожалению в работе никак не затронута работы с контекстами, а это первая часть спринта.

2024-08-14 08:08 UTC, tmvrus commented on cmd/shortener/main.go
> +			panic("Ooops")
в это месте у приложения уже есть логер, следует использовать его
более того, пользователю наверняка захочется видеть что-то более информативное чем Ooops

2024-08-14 08:08 UTC, tmvrus commented on cmd/shortener/main.go
> +	fmt.Println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
тем логирования обсуждалась в предыдущем спринте, с тех пол fmt для логорования не предназначен

2024-08-14 08:08 UTC, tmvrus commented on cmd/shortener/main.go
> +
выглядит довольно странно, если случается ошибка, то это никак не влияет на работу ф-и
более того, ф-я может вернуть nil, nil и вызывающий код это вообще никак не учитывает

2024-08-14 08:08 UTC, tmvrus commented on internal/app/handler/batch/batch_handler.go
> +	Batch(request *[]ButchRequest) (*[]entity.ShortURLEntity, error)
нет большого смысла передавать слайсы по ссылке, слайс уже сам по себе ссылочный тип

2024-08-14 08:08 UTC, tmvrus commented on internal/app/handler/batch/batch_handler.go
> +type ButchURLServiceInterface interface {
в Go не особо принято давать интерфейсам постфиксы *Interface, по крайней мере в стандартной библиотеке я этого не встречал

2024-08-14 08:08 UTC, tmvrus commented on internal/app/repository/postgres/migration/0002_add_short_url_table.up.sql
> +CREATE TABLE IF NOT EXISTS url
выглядит как лишняя миграция

2024-08-14 08:08 UTC, tmvrus commented on internal/app/repository/postgres/postgres.go
> +}
если два разных запроса захотят одновременно использовать транзакции, будет конфликт

2024-08-14 17:53 UTC, arturturundaev commented on cmd/shortener/main.go
> +			panic("Ooops")
Согласен, материал был дан, но в задании на инкремент не было указано, что необходимо реализовать.
Добавил в API /ping

2024-08-14 17:58 UTC, arturturundaev commented on cmd/shortener/main.go
> +	fmt.Println("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
Прошу прощения, отладочные логи. Не должны были попасть в mr

2024-08-14 18:02 UTC, arturturundaev commented on cmd/shortener/main.go
> +
Добавил проверку на nil и логирование

2024-08-14 18:06 UTC, arturturundaev commented on internal/app/handler/batch/batch_handler.go
> +	Batch(request *[]ButchRequest) (*[]entity.ShortURLEntity, error)
+

2024-08-14 18:13 UTC, arturturundaev commented on internal/app/handler/batch/batch_handler.go
> +type ButchURLServiceInterface interface {
Переименовал все интерфейсы с соответствии с https://go.dev/doc/effective_go#interface-names

2024-08-14 18:14 UTC, arturturundaev commented on internal/app/repository/postgres/migration/0002_add_short_url_table.up.sql
> +CREATE TABLE IF NOT EXISTS url
Согласен, в первой миграции создается таблица

2024-08-14 19:39 UTC, arturturundaev commented on internal/app/repository/postgres/postgres.go
> +}
Воспроизвел ошибку, о который ты писал.
Исправил, но пришлось запихнуть внутрь репозитория логику разделения массива на части и вставки части в БД. И внутрь ушла логика по транзакциям.

Пытался оставить логику разделения и вызов транзакций оставить в сервисе, но из-за интерфейсов не получилось

2024-08-15 12:52 UTC, tmvrus commented on cmd/shortener/main.go
> +			panic("Ooops")
А про панику там что-то было

2024-08-15 14:30 UTC, tmvrus approved these changes

2024-08-17 18:48 UTC, merged